### ISSUE TITLE
Corrupted access token

### ISSUE THREAD

**Issue by alienware** [segmind/edge_tutorials#3]
# WHAT
- `import edge` leads to the following error after `~/.segmind/secret.file` setup
![Getting started error](https://user-images.githubusercontent.com/2356208/80709186-82495800-8b0a-11ea-9143-11ee4ed58044.png)

**Comment by alienware** [comment]
@rohitrameshrao Any pointers how to get fix this issue?

**Comment by rohitrameshrao** [comment]
We have a bugfix in 0.4.0 to avoid the issue. You can download .whl file for 0.4.0 from [here](https://segmind-data.s3.ap-south-1.amazonaws.com/edge/dist/edge-0.4.0/edge-0.4.0.dev0-cp36-cp36m-linux_x86_64.whl).

**Comment by alienware** [comment]
I'm facing this on 0.4.0-dev only, looks like either the AWS secret token that you use is now deactivated or my email-password combination is not working.
![Screenshot from 2020-04-30 21-53-45](https://user-images.githubusercontent.com/2356208/80734747-3d82e880-8b2d-11ea-82ee-f7b34bf28b86.png)

**Comment by pratik-segmind** [comment]
@alienware , can you try the following:
 

1.  `rm ~/.segmind/tokens.file`, then re-run the script

else

1.  `pip3 uninstall edge`
2.  wget https://segmind-data.s3.ap-south-1.amazonaws.com/edge/dist/edge-0.4.0/edge-0.4.2.dev0-cp36-cp36m-linux_x86_64.whl
3.  pip3 install edge-0.4.2.dev0-cp36-cp36m-linux_x86_64.whl

**Comment by alienware** [comment]
Removing the `~/.segmind/tokens.file` worked, thanks a bunch!
